#!/usr/bin/env bash
#Bash script that displays the PID, along with the process name, of processes whose name contain the word bash.
echo "Processes containing 'bash':"
pgrep -f bash | while read -r pid; do
    pname=$(ps -p "$pid" -o comm=)
    echo "PID: $pid, Name: $pname"
done
